### ISSUE TITLE
Can't drag & drop XML

### ISSUE THREAD

**Issue by Ozy311** [dolkensp/HoloXPLOR#3]
I tried both Chrome and MS Edge and neither upload when the XML is dragged onto the page or onto the popup on the page.   Permission issues?

**Comment by dolkensp** [comment]
Can you email me the xml - plugins@ddrit.com

There's currently no feedback if there's a problem uploading - and there is *some* validation of what is uploaded (Basically, MUST be an XML file, and the XML serializer MUST be able to read it, otherwise it ignores the file)

If you send me your file, I can see why it wouldn't upload.

**Comment by dolkensp** [comment]
Please try this again - I've added some feedback states to the upload, along with both frontend and backend error logging - should help determine any problems.

**Comment by dolkensp** [comment]
Some people have reported issues when running their browser in admin-mode.

Need to add a manual upload button for those who can't drag/drop

**Comment by dolkensp** [comment]
Manual Upload functionality has been added - click upload, then click browse to use
