### ISSUE TITLE
Hornet Size 4 Fixed Ball Turret

### ISSUE THREAD

**Issue by Gamewiz** [dolkensp/HoloXPLOR#6]
Just wanted to let you know, when you place the Size 4 Fixed Turret on the Super Hornet, it does not open up a size 4 weapon slot, making the fixed turret effectively useless since you can't equip anything into it. You can put the ball turret back and you'll have the two size 2 weapon slots open back up, but no matter how you try to get that size 4 weapon slot to create itself, it won't.

**Comment by dolkensp** [comment]
Try deleting your XML file and re-downloading it from CIG (By re-launching your hangar)

This one is actually a bug on CIG / your XML, I've seen it a few times, where your inventory has a Fixed Turret that doesn't actually have any slots.

**Comment by dolkensp** [comment]
Going to try and patch/fix XML files with this bug in the future

**Comment by stevencheatham** [comment]
I only get this issue if I load the fixed turret in HaloXPLOR.  It never opens up the S4 slow. Works fine in the Halo Table everytime.

**Comment by dolkensp** [comment]
@stevencheatham yup - When rental items come down from turbulent, they're actually missing a bunch of XML - I'm hoping to add the missing XML parts to it, which I assume is what the HoloTable does.

HoloXPLOR traditionally just moved XML chunks around, rather than adding/deleting anything new, but as more people try to use rental gimbals, it's become apparent that I'll need to patch this, especially now that people can't "unlock" the slot in the HoloTable first.

**Comment by dolkensp** [comment]
This should be fixed - let me know if it's still an issue
